app/__init__.py
from . import factory

app/admin/__init__.py
"""
"""
from flask import Blueprint

admin = Blueprint('admin', __name__, template_folder='templates')

from . import views

app/admin/views.py
from flask import render_template
from . import admin

@admin.route("/")
def index():
    
    return render_template("admin_index.html")

app/templates/base.html
<!doctype html>
<title>BP</title>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" type="text/css" href="/static/node_modules/bootstrap/dist/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/static/css/style.css"/>

{% block basehead %}
{% endblock %}

</head>

<body>

    <nav class="navbar navbar-default navbar-fixed-top">
       <div class="container">
         <div class="navbar-header">
           <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
             <span class="sr-only">Toggle navigation</span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
             <span class="icon-bar"></span>
           </button>
          <a class="navbar-brand topnav" href="{{ url_for('public.index') }}">Blueprints Example</a>
    
         </div>
         <div id="navbar" class="navbar-collapse collapse">
      
          <ul class="nav navbar-nav navbar-right">

                <li {% if 'index' == active_page %} class="active"{% endif %}>
                  <a href="{{ url_for('public.index') }}">public</a>
                </li>

                <li {% if 'admin' == active_page %} class="active"{% endif %}>
                    <a href="{{ url_for('admin.index') }}">admin</a>
                </li>
              
          </ul>
         </div>
       </div>
    </nav>


     {% block content %}
     {% endblock %}


</body>
</html>